site_name: M0226 - Seguretat Informàtica
theme:
  name: material
  language: ca # Configura la web en català

nav:
  - Inicio: index.md
  - "RA1: Seguretat Passiva": 
    - "Conceptes Generals": docs/ra1/conceptos.md
    - "Seguretat Física i Lògica":
      - "Índex": docs/ra1/seguretat-fisica-logica/index.md
      - "Seguretat Física": docs/ra1/seguretat-fisica-logica/seguretat-fisica.md
      - "Seguretat Lògica": docs/ra1/seguretat-fisica-logica/seguretat-logica.md
    - "Centre de Processament de Dades (CPD)":
      - "Índex CPD": docs/ra1/cpd/index_cpd.md
      - "Ubicació Geogràfica": docs/ra1/cpd/ubicacio-geografica.md
      - "Ubicació dins l'Edifici": docs/ra1/cpd/ubicacio-edifici.md
      - "Infraestructura Tècnica": docs/ra1/cpd/infraestructura-tecnica.md
      - "Checklist": docs/ra1/cpd/checklist.md
    
  - "RA2: Emmagatzament de la informació":
    - "Criptografia": docs/ra2/cripto.md
    
  - "RA3: Seguretat Activa":
    - "Polítiques de Seguretat": docs/ra3/politicas.md
    - "ACL Windows": docs/ra3/acl_windows.md
    - "Autenticació": docs/ra3/autenticacio.md
    - "Contrasenyes": docs/ra3/contrasenyes.md
