site_name: M0226 - Seguretat Informàtica
site_description: Apunts organitzats per RA

theme:
  name: material
  language: es # Traduce los botones y el buscador al español
  palette: 
    # Configura colores oscuros/claros estilo hacker de seguridad
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Cambiar a modo claro
  features:
    - navigation.tabs # Menú superior moderno
    - search.suggest  # Buscador inteligente que autocompleta

nav:
  - Inicio: index.md
  - "RA1: Seguretat Passiva": 
    - "Conceptes Generals": ra1/conceptos.md
    - "Còpies de Seguretat": ra1/backups.md
  - "RA2: Seguretat Activa":
    - "Criptografia": ra2/cripto.md
